project:
  type: website

website:
  title: "Muscle Memory Data Science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/prashanth-sriram
      - icon: twitter
        href: https://twitter.com/prashanthsriram/
      - icon: linkedin
        href: https://www.linkedin.com/in/prashanth-sriram-459ba231/ 

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

